[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "MPESA_TZ_ENV,NEXT_PUBLIC_SHOP_LAT,NEXT_PUBLIC_SHOP_LNG,NEXT_PUBLIC_SHOP_PHONE,NEXT_PUBLIC_WHATSAPP_NUMBER,NEXT_PUBLIC_SITE_URL"
